### ISSUE TITLE
sner tagger output different to averaged_perceptron_tagger

### ISSUE THREAD

**Issue by stephenrt42** [caihaoyu/sner#1]
Hello,

Noticed that the Tag output provide by the SNER is slightly off compared to the average_perceptron_tagger.

Here's an example of my code:

`import nltk
from nltk.tag import StanfordNERTagger
from nltk.tokenize import word_tokenize
from nltk import pos_tag
from nltk.chunk import conlltags2tree
from nltk.tree import Tree

nltk.download('averaged_perceptron_tagger')
nltk.download('punkt')

stanford_dir = '/home/ds/notebooks/stanford-ner-2016-10-31/'
jarfile = stanford_dir + 'stanford-ner.jar'
modelfile = stanford_dir + 'classifiers/english.all.3class.distsim.crf.ser.gz'

st = StanfordNERTagger(model_filename=modelfile, path_to_jar=jarfile)`
text = 'Intellectual Property at Shire Pharmaceuticals'

tokenized_text = word_tokenize(text)
classified_text = st.tag(tokenized_text)

print(classified_text)
[('Intellectual', 'O'), ('Property', 'O'), ('at', 'O'), ('Shire', 'ORGANIZATION'), ('Pharmaceuticals', 'ORGANIZATION')]

Now if I use the SNER with the same sentence, my tag output is the following:

[('Intellectual', 'ORGANIZATION'), ('Property', 'ORGANIZATION'), ('at', 'ORGANIZATION'), ('Shire', 'ORGANIZATION'), ('Pharmaceuticals', 'ORGANIZATION'), ("'", 'O')]

**Comment by caihaoyu** [comment]
hi stephenrt42:

I'm so sorry to reply to you so late.

The problem is because **nltk** use `edu.stanford.nlp.process.WhitespaceTokenizer` as tokenizerFactory.

You can just change `ner-server` parameter like this:

```bash
java -Djava.ext.dirs=./lib -cp stanford-ner.jar edu.stanford.nlp.ie.NERServer -port 9199 -loadClassifier ./classifiers/english.all.3class.distsim.crf.ser.gz -tokenizerFactory edu.stanford.nlp.process.WhitespaceTokenizer -tokenizerOptions tokenizeNLs=false
```
I changed `readme` file. 

Hope this can help you.

Sorry again so late reply.

**Comment by stephenrt42** [comment]
No, that's great. Thank you!

Stephen Theobald
