### ISSUE TITLE
Return values being deleted

### ISSUE THREAD

**Issue by StridentDefender32** [caihaoyu/sner#2]
Hey there, while using this I noticed that values would be deleted from the string returned by the Stanford server. Any word that contained a '/' would simply disappear. It's caused by your use of s.split in forming the return value (because any word with a '/' in it will cause the length check of the resulting list to fail).

This is easily resolved by using the proper string method s.rsplit, with a max split argument of 1.

```
def __get_entities(self, text):
    return [tuple(s.rsplit('/', 1))
        for s in text.strip().split(' ') if len(s.rsplit('/', 1)) == 2]
```

**Comment by caihaoyu** [comment]
I fixed this bug in 0.2.1 version.

Thank you for your help.
