### ISSUE TITLE
Possible to change the tokenizer or tag a pre-tokenized list?

### ISSUE THREAD

**Issue by bsugerman** [caihaoyu/sner#3]
Hi Haoyu, 

Thank you so much for writing and maintaining this package. It is incredibly useful! But I have a question. As I discuss on [stackoverflow](https://stackoverflow.com/questions/45415408/can-i-stop-stanford-pos-and-ner-taggers-from-removing-and-characters) the server is stripping off a lot of characters that I want to keep (#, @, http://) and this seems to be happening by whatever internal tokenizer it is using. However, if i use Stanford's tagger within NLTK, these are kept. So I'm wondering if you know how to change the tokenizer that the NER server uses, or how to feed in a pre-tokenized list of strings rather than the whole sentence as a character string. 

This could be a really useful feature to add to sner.

-ben

**Comment by caihaoyu** [comment]
Hi ben:

The problem is because of nltk use edu.stanford.nlp.process.WhitespaceTokenizer as tokenizerFactory.

You can just change ner-server parameter like this:

```
java -Djava.ext.dirs=./lib -cp stanford-ner.jar edu.stanford.nlp.ie.NERServer -port 9199 -loadClassifier ./classifiers/english.all.3class.distsim.crf.ser.gz -tokenizerFactory edu.stanford.nlp.process.WhitespaceTokenizer -tokenizerOptions tokenizeNLs=false
```

Hope this can help you.
